### ISSUE TITLE
Problem with SEDs in unbinned mode

### ISSUE THREAD

**Issue by jballet** [fermi-lat/pyLikelihood#16]
I have a weird problem when creating SEDs starting from an existing "like" object covering a large energy range, when it involves unbinned data. They converge with lots of difficulty in Minuit, sometimes not at all, even when the unbinned data should not be involved (ie, the energy bin is outside that covered by the unbinned data). After many attempts to simplify the problem, I think the problem lies with the setEnergyRange(emin,emax) call and I have managed to show a similar behavior in a pure unbinned case.
The attached test harness contains a python script (testSEDUnbinned.py) that loads an unbinned data set, fits it, then selects a smaller energy range and refits, as is done for an SED.
The model is very simple (only one source normalization free and the isotropic normalization).
The full events list (MergedEVENTS_1001.fits) covers the range 30 GeV to 1 TeV.
The output is in testSEDUnbinned.log.
The first Minuit fit (over the full energy range) works fine, but the second fit (after energy selection between 30 and 100 GeV) does not. Even if it converges and provides the right answer in the end, there are many worrying messages like "MIGRAD TERMINATED WITHOUT CONVERGENCE" and it has to resort to the SIMPLEX method.
To prove that this is not normal behavior, I have extracted the same energy range (30 to 100 GeV) in MergedEVENTS_1001_SUB100.fits and run the same script (uncomment the second evfile definition).
The output is in testSEDUnbinned_SUB100.log.
The fit works fine and again after energy selection (which does nothing in that case).
It finds the same result as in testSEDUnbinned.log, but without any worrying message.
Comparing the logs it looks like the values in the "FIRST DERIVATIVE" column written by MIGRAD could be the cause of the difficult convergence.
I repeat that even though in that particular very simple case the correct result is found in the end, the SED fits often fail entirely in my more complex cases.
[testSEDUnbinned.zip](https://github.com/fermi-lat/pyLikelihood/files/4701048/testSEDUnbinned.zip)

**Comment by eacharles** [comment]
It there any reason you absolutely need to use unbinned analysis?   If this is just a question of trying to get a bit more performance I'm afraid I don't have the time to support it.

**Comment by jballet** [comment]
Well, the reason I use unbinned analysis is to avoid creating huge files, while keeping the PSF resolution and the event type information (we already had that discussion). I am not asking any new development, only that the existing software should work normally.
I am not alone in using unbinned analysis, most people working on short-term transients use unbinned analysis and this is big business now.

**Comment by eacharles** [comment]
This is probably going to take a long time to track down (a couple weeks).  I only have a small fraction of my time to work on fermi and the unbinned likelihood code is very complicated and slow to debug.

**Comment by eacharles** [comment]
First, I noticed that if use the numericDerivs flag in the fit, it seems to converge.    Is this generally the case?  

I'm doing:

like.fit(numericDerivs=True)

**Comment by eacharles** [comment]
I'm afraid that it seems to me like there are a number of things wrong with the LogLike class.  Setting the energy range changes the parameters m_emin and m_emax, however, those parameters are only used the the LogLike.value() function, and only to decide which event to exclude from the log (source model) term.   They are not used in the computation of the numeric derivatives, or in the computation of the Npred terms.

**Comment by eacharles** [comment]
Even if we include a cut on m_emin and m_emax in the numeric derivative, shouldn't the energy cuts also be used somehow in conputing the NPred terms?

**Comment by eacharles** [comment]
Adding a cut on the energy to the event loop at least gets the fits to converge in the test case.  But I'm still thinking that changing the energy ranges should affect the NPred terms.

**Comment by eacharles** [comment]
Ok, I see how the energies are getting into the NPred calculation (it is via the Source::computeExposure() calls).   It looks like for the particular test case I was using the NPred value after the refit was extremely close to the original value.

**Comment by eacharles** [comment]
So, at thls point I'm going to say that I'm really not sure that that I've solved the problem, (as I said, the LogLikelihood class is complicated and it's hard to see how the energy bound are being propagated), but at least I solved the most glaring aspect of it (that the energy cuts weren't being used in the numeric derivatives).    I can commit those changes for further testing.

**Comment by jballet** [comment]
Thank you, Eric.
A problem with the derivatives is indeed fully compatible with what I saw (convergence problems, but often reaching the correct answer in the end). I will be happy to test it at large scale if it can be included in the python 2.7 beta release.

**Comment by jballet** [comment]
I could not test that in FT 1.3.1 because unbinned mode was completely broken (Likelihood #84).
I don't see any change in FT 1.3.4. The convergence is just as difficult as it was.
Are you sure the change has been integrated?

**Comment by jballet** [comment]
I tested FT 1.3.5 and it converges fine now.
